### ISSUE TITLE
Two plugins still use deprecated EMFIndexRetrieval

### ISSUE THREAD

**Issue by lwrage** [smaccm/smaccm#176]
EMFIndexRetrieval will be removed for OSATE 2.3.6 because it causes all kind of problems, see osate/osate2#1036

It is still used in two places:

- com.rockwellcollins.atc.tcg.util.TcgUtils
- edu.uah.rsesc.aadlsimulator.ui.launch.SimulationTab

**Comment by lwrage** [comment]
The two places should effectively inline the code that is executed in EMFIndexRetrieval. The ResourceDescriptionsProvider must be injected. If necessary we can help with the injector stuff (don't get an injector form Osate2CorePlugin, see osate/osate2#1467).

**Comment by kfhoech** [comment]
Thanks for the information.  

Since these locations are looking for items the global scope, would it be appropriate to use the Aadl2GlobalScopeUtil?

One hair with these locations is that a context is not readily available.  To work around this, I used the org.osate.aadl2.modelsupport.modeltraversal.TraverseWorkspace.getAadlFilesInWorkspace() method to get all the AADL files and then iterated over them, using the top-level ModelUnit in each as the context.  However, for the TcgUtils, this may be an incorrect approach since it considers the workspace rather than the current project.  For the SimulationTab, this is merely inefficient as it is filtered by project. 

Is there a better way to access the scope provider based on knowledge of the current project?

**Comment by lwrage** [comment]
The global scope depends on the AADL project. It's the project and the project dependencies, so it cannot work on a workspace level.

To search in the workspace independent of projects I would iterate through the resource descriptions and find the exported objects. This is what happens in EMFIndexRetrieval. One problem with EMFIndexRetrieval is that it uses static methods such that dependency injection doesn't work, and there is a hack elsewhere to set the ResourceDescriptionsProvider.

The advantage of that approach is that it doesn't need to load the aadl files into memory. The resource descriptions are cached on disk (in directory .aadlbin-gen).

**Comment by kfhoech** [comment]
Resolved by #179
