### ISSUE TITLE
Data type error not caught by validator

### ISSUE THREAD

**Issue by janetlj** [smaccm/smaccm#48]
When declaring a data implementation with subcomponents of an abstract type (no implementation nor extending a base type) in AGREE, the validator did not flag it as an error, but when running "verify single layer" in AGREE, the system threw an "assertion failed" exception.

**Comment by kfhoech** [comment]
Are you describing something like the following?

package Data_Type_Error_48
public

    data Incomplete
    end Incomplete;

    system Internal_System
        features
            inp : in data port Incomplete;
            outp : out data port Incomplete;
        annex agree {**
            guarantee "Trivial" : true;
        **}; 
    end Internal_System;

    system Simple_System
        features
            inp : in data port Incomplete;
            outp : out data port Incomplete;
        annex agree {**
            guarantee "Trivial" : true;
        **}; 
    end Simple_System;

    system implementation Simple_System.Impl
        subcomponents
            inner : system Internal_System;
        connections
            inc : port inp -> inner.inp;
            outc : port inner.outp -> outp;
    end Simple_System.Impl;

end Data_Type_Error_48;

This does not throw an error in AGREE "Verify Single Layer"   However, there's not much that can be done in AGREE since there is no mapping of the data type to concrete types for analysis.

Is there something more specific you can share regarding the problem?  Or, is there more detailed error information?

**Comment by backesj** [comment]
Hi Karl,

I asked Janet to put this here after a bug she showed me. The issue occurs
when you have data implementations with subcomponents that are other data
types that do not extend any of the base types that AGREE reasons about.
AGREE throws an exception during analysis in this case. We should add some
code so that this does not pass validation.

- John

**Comment by kfhoech** [comment]
Ok.  I see what I missed in Janet's description of the problem.

Here's an example that should duplicate the problem:

package Data_Type_Error_48
public
    with Base_Types;

    data Incomplete
    end Incomplete;

    data Aggregate
    end Aggregate;

    data implementation Aggregate.Impl
        subcomponents
            a : data Incomplete;
            b : data Base_Types::Integer;
    end Aggregate.Impl;

    system Internal_System
        features
            inp : in data port Aggregate.Impl;
            outp : out data port Aggregate.Impl;
        annex agree {**
            guarantee "Internal Trivial" : true;
            guarantee "Internal numeric result" : outp.b = inp.b + 1;
        **}; 
    end Internal_System;

    system Simple_System
        features
            inp : in data port Aggregate.Impl;
            outp : out data port Aggregate.Impl;
        annex agree {**
            guarantee "Trivial" : true;
            guarantee "Numeric result" : outp.b > inp.b;
        **}; 
    end Simple_System;

    system implementation Simple_System.Impl
        subcomponents
            inner : system Internal_System;
        connections
            inc : port inp -> inner.inp;
            outc : port inner.outp -> outp;
    end Simple_System.Impl;

end Data_Type_Error_48;

And, this does result in a null pointer exception when analysis is attempted.

**Comment by backesj** [comment]
Thanks for the example Karl. This looks exactly like the issue that Janet
ran into. Unfortunately this is going to be a bit of a pain to add
validation for. If I have extra cycles by the end of this week I'll be sure
to fix this.

- John

**Comment by kfhoech** [comment]
It appears that @backesj fixed this problem in c547f29e8e7b4fc0e959b890b5b1237141b3bca5.

Abstract types are now ignored in formulation of the analysis.
